projectName = "Camping"
tagline = "A Roblox developer sandbox using Rojo v7 fully managed setup"
gitSourceBranch = "main"

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = "/favicon.png"
url = "https://matyasjay.github.io"
baseUrl = "/campingsite"

[[classOrder]]
classes = ["Introduction"]


[[classOrder]]
section = "Items"
collapsed = true
classes = ["Fire Pit"]

[[classOrder]]
section = "Toolkits"
collapsed = true
classes = ["Animate", "Iterator", "Observer", "Persona", "Trigger"]

[[classOrder]]
section = "User Interface"
collapsed = true
classes = ["StatsGui", "GameGui"]

[[classOrder]]
classes = ["Animations"]

[[classOrder]]
section = "Variables"
collapsed = true
classes = ["Attributes", "Attributes Config","Statistics","Statistics Config" ]

[[classOrder]]
classes = ["Remote"]

[footer]
style = "dark"
copyright = "&nbsp;"

[[footer.links]]
title = "Useful Links"

[[footer.links.items]]
label = "Roblox Engine"
to = "https://create.roblox.com/docs/reference/engine"

[[footer.links.items]]
label = "Rojo v7"
to = "https://rojo.space/docs/v7/"

[[footer.links.items]]
label = "Moonwave"
to = "https://eryn.io/moonwave/docs/intro"

[[footer.links.items]]
label = "Infima"
to = "https://github.com/facebookincubator/infima/tree/main"


