on:
  workflow_dispatch:
  push:
    branches: ["main"]
jobs:
  status:
    runs-on: ubuntu-latest
    name: Build Rojo Project
    steps:
      - name: Checkout files
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BUILD_TOKEN }}
      - name: Make
        run: |
          make build
      - name: Build
        uses: CompeyDev/rojo-build-action@0.1.5
        with:
          output: build/latest
          type: rbxm
      - name: Commit and Push
        run: |
          git config --global user.email "bot@gtihub"
          git config --global user.name "Bot"
          git diff --quiet build/latest.rbxm || (git add build/latest.rbxm && git commit -m "chore(deploy): build rojo project" && git push)
