on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.BUILD_TOKEN }}
      - uses: laputansoft/github-tag-action@v4.6
        with:
          github_token: ${{ secrets.BUILD_TOKEN }}
          tag: ${{ steps.package-version.outputs.version }}
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.BUILD_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          make build
      - uses: softprops/action-gh-release@v2
